ReleaseCandidateTracker/Models/ReleaseCandidate.cs
using System;
using System.Collections.Generic;

namespace ReleaseCandidateTracker.Models
{
    public class ReleaseCandidate
    {
        public string FullVersion { get { return ProductName + "-" + VersionNumber; } }
        public string ProductName { get; set; }
        public DateTime CreationDate { get; set; }
        public ReleaseCandidateState State { get; set; }
        public string VersionNumber { get; set; }
        public IList<ReleaseCandidateHistoryItem> History { get; set; }
        public IList<ReleaseCandidateDeployment> Deployments { get; set; }

        public ReleaseCandidate()
        {
            History = new List<ReleaseCandidateHistoryItem>();
            Deployments = new List<ReleaseCandidateDeployment>();
        }

        public void UpdateState(ReleaseCandidateState newState)
        {
            History.Add(new ReleaseCandidateHistoryItem
                            {
                                Date = DateTime.UtcNow,
                                StateChange = string.Format("Changed state from {0} to {1}.", State, newState)
                            });
            State = newState;
        }

        public void MarkAsDeployed(bool success, DeploymentEnvironment environment)
        {
            var deploymentDate = DateTime.UtcNow;
            History.Add(new ReleaseCandidateHistoryItem
                            {
                                Date = deploymentDate,
                                StateChange = string.Format("Deployed to {0} environment.", environment.Name)
                            });
            Deployments.Add(new ReleaseCandidateDeployment
                                {
                                    Date = deploymentDate,
                                    Environment = environment.Name
                                });
            environment.RecordDeployment(VersionNumber, success);
        }        
    }
}

ReleaseCandidateTracker/ViewModels/ReleaseCandidateViewModel.cs
using ReleaseCandidateTracker.Models;

namespace ReleaseCandidateTracker.ViewModels
{
    public class ReleaseCandidateViewModel
    {
        public ReleaseCandidate Candidate { get; set; }
        public string ReleaseNotes { get; set; }
    }
}

ReleaseCandidateTracker/Controllers/EnvironmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReleaseCandidateTracker.Models;

namespace ReleaseCandidateTracker.Controllers
{
    public class EnvironmentController : BaseController
    {
        public ActionResult Index()
        {
            return View(DocumentSession
               .Query<DeploymentEnvironment>()
               .OrderBy(x => x.Name)
               .ToList());
        }

        public ActionResult Details(string name)
        {
            var environment = DocumentSession.GetEnvironment(name);
            return View(environment);
        }

        public ActionResult Create()
        {
            return View();
        } 

        [HttpPost]
        public ActionResult Create(DeploymentEnvironment environment)
        {
            DocumentSession.Store(environment, environment.Name.MakeEnvironmentId());
            return RedirectToAction("Index");
        }        
    }
}

ReleaseCandidateTracker/Controllers/ReleaseCandidateApiController.cs
using System;
using System.Web.Mvc;
using ReleaseCandidateTracker.Models;
using System.Linq;
using Raven.Client.Linq;

namespace ReleaseCandidateTracker.Controllers
{
    public class ReleaseCandidateApiController : ApiController
    {        
        [HttpPost]
        public ActionResult UpdateState(string versionNumber, ReleaseCandidateState state)
        {
            var candidate = DocumentSession.GetCandidate(versionNumber);
            candidate.UpdateState(state);
            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult List()
        {
            var candidates = DocumentSession
                .Query<ReleaseCandidate>()
                .OrderByDescending(x => x.CreationDate)
                .Take(20)
                .ToList()
                .Select(x => string.Format("{0};{1};{2};{3}",x.ProductName, x.VersionNumber,x.State,x.CreationDate.ToString("s")));

            return new ContentResult
                       {
                           Content = "ProductName;Version;State;CreationDate\r\n" + string.Join("\r\n", candidates)
                       };
        }

        [HttpPut]
        public ActionResult GetVersion(string name)
        {
            var environemt = DocumentSession.GetEnvironment(name);
            return new ContentResult
            {
                Content = environemt.CurrentVersion
            };
        }

        [HttpPost]
        public ActionResult MarkAsDeployed(string versionNumber, string environment, bool success)
        {
            var candidate = DocumentSession.GetCandidate(versionNumber);
            var env = DocumentSession.GetEnvironment(environment);
            candidate.MarkAsDeployed(success, env);
            return new EmptyResult();
        }

        [HttpPost]
        public ActionResult Create(ReleaseCandidateCreateModel formPost)
        {
            var candidate = new ReleaseCandidate
            {
                CreationDate = DateTime.UtcNow,
                VersionNumber = formPost.VersionNumber,
                ProductName = formPost.ProductName,
                State = formPost.State
            };
            var candidateId = candidate.FullVersion.MakeCandidateId();
            var existing = DocumentSession.Load<ReleaseCandidate>(candidateId);
            if (existing != null)
            {
                throw new HttpException(409, string.Format("Release candidate {0} already exists", candidate.VersionNumber));
            }
            DocumentSession.Store(candidate, candidateId);
            return new EmptyResult();
        }

        
        [HttpPut]
        public ActionResult AttachDocument(string versionNumber, string documentName, string contentType)
        {
            DocumentSession.PutAttachment(versionNumber.MakeCustomDocumentKey(documentName), contentType, Request.InputStream);
            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult GetDocument(string versionNumber, string documentName)
        {
            var doc = DocumentSession.GetAttachmentResult(versionNumber.MakeCustomDocumentKey(documentName));
            return doc ?? new HttpNotFoundResult(string.Format("No {0} associated with release candidate {1}", documentName, versionNumber));
        }

        [HttpPut]
        public ActionResult AttachScript(string versionNumber)
        {
            return AttachDocument(versionNumber, "deploy.ps1", "text/plain");
        }

        [HttpGet]
        public ActionResult GetScript(string versionNumber)
        {
            return GetDocument(versionNumber, "deploy.ps1");
        }


        [HttpPut]
        public ActionResult AttachReleaseNotes(string versionNumber)
        {
            return AttachDocument(versionNumber, "release-notes.txt", "text/plain");
        }

        [HttpGet]
        public ActionResult GetReleaseNotes(string versionNumber)
        {
            return GetDocument(versionNumber, "release-notes.txt");
        }
    }
}

ReleaseCandidateTracker/Controllers/ReleaseCandidateController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Raven.Client.Linq;
using ReleaseCandidateTracker.Models;
using ReleaseCandidateTracker.ViewModels;

namespace ReleaseCandidateTracker.Controllers
{
    public class ReleaseCandidateController : BaseController
    {
        public ActionResult Index(int? page)
        {
            var settings = DocumentSession.GetSettings();

            decimal totalCount = DocumentSession
                .Query<ReleaseCandidate>()
                .Count();

            var query = DocumentSession
                .Query<ReleaseCandidate>()
                .OrderByDescending(x => x.CreationDate);

            var environments = DocumentSession
                .Query<DeploymentEnvironment>()
                .ToList();

            var allCandidates = page.HasValue && page.Value > 0
                                    ? GetPagedResult(page.Value, settings.PageSize, query)
                                    : query.Take(settings.PageSize).ToList();

            var currentPage = page ?? 1;
            var pageCount = (int)Math.Ceiling(totalCount / (decimal) settings.PageSize);
            return View(new ReleaseCandidateListViewModel
                            {
                                Items = allCandidates,
                                Page = currentPage,
                                Environments = environments,
                                First = currentPage == 1,
                                Last = currentPage == pageCount
                            });
        }

        private static List<ReleaseCandidate> GetPagedResult(int page, int pageSize, IRavenQueryable<ReleaseCandidate> query)
        {
            return query
                .Skip((page - 1)*pageSize)                    
                .Take(pageSize)
                .ToList();
        }

        [HttpGet]
        public ActionResult Deploy(string versionNumber)
        {
            var settings = DocumentSession.GetSettings();
            if (string.IsNullOrEmpty(settings.DeploymentWorkingDirectory))
            {
                TempData["Message"] = "Please specify deployment working directory";
                return RedirectToAction("Edit", "Settings");
            }

            var deployScriptKey = versionNumber.MakeCustomDocumentKey("deploy.ps1");
            var deployScript = DocumentSession.Advanced.DatabaseCommands.GetAttachment(deployScriptKey);

            using (var fileStream = System.IO.File.Create(Path.Combine(settings.DeploymentWorkingDirectory, deployScriptKey)))
            {
                deployScript.Data().CopyTo(fileStream);
            }

            var uniqueId = Guid.NewGuid().ToString();
            var listenUrl = string.Format("http://{0}:12345/{1}", Environment.MachineName, uniqueId);
            var startInfo = new ProcessStartInfo(Path.Combine(settings.DeploymentWorkingDirectory, "PowerShellHtmlConsole.exe"),
                string.Format(@"--listen={0} --script=.\{1}", listenUrl,deployScriptKey));
            startInfo.WorkingDirectory = settings.DeploymentWorkingDirectory;
            Process.Start(startInfo);
            Thread.Sleep(5000);
            return Redirect(listenUrl + "/console.htm");
        }

        [HttpGet]
        public ActionResult Details(string versionNumber)
        {
            var candidate = DocumentSession.GetCandidate(versionNumber);            
            string releaseNotesText = "";
            var notesAttachment = DocumentSession.Advanced.DatabaseCommands.GetAttachment(versionNumber.MakeCustomDocumentKey("release-notes.txt"));
            if (notesAttachment != null)
            {
                using (var stream = notesAttachment.Data())
                {
                    releaseNotesText = new StreamReader(stream).ReadToEnd();
                }
            }
            return View(new ReleaseCandidateViewModel
                            {
                                Candidate = candidate,                                
                                ReleaseNotes = FormatReleaseNotesForHtml(releaseNotesText)
                            });
        }

        private static string FormatReleaseNotesForHtml(string releaseNotesText)
        {
            var items = releaseNotesText.Split(new[] {'\n', '\r'}, StringSplitOptions.RemoveEmptyEntries);
            return "<ul>" + string.Join(Environment.NewLine, items.Select(x => "<li>" + x.TrimStart(' ','*') + "</li>")) + "</ul>";
        }

        [HttpGet]
        public ActionResult Edit(string versionNumber)
        {
            var candidate = DocumentSession.GetCandidate(versionNumber);
            return View(candidate);
        }

        [HttpPost]
        public ActionResult Edit(string versionNumber, ReleaseCandidateState state)
        {
            var candidate = DocumentSession.GetCandidate(versionNumber);
            candidate.UpdateState(state);
            return RedirectToAction("Index");
        }
    }
}

ReleaseCandidateTracker/Views/ReleaseCandidate/Details.cshtml
@model ReleaseCandidateTracker.ViewModels.ReleaseCandidateViewModel

@{
    ViewBag.Title = "Details of release candidate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details of @Model.Candidate.ProductName @Model.Candidate.VersionNumber</h2>
<div class="rightColumn">
<h3>Release notes</h3>
@Html.Raw(Model.ReleaseNotes)
</div>
<fieldset class="leftColumn">
    <div class="display-label">Product Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Candidate.ProductName)
    </div>

    <div class="display-label">Creation Date (UTC)</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Candidate.CreationDate)
    </div>

    <div class="display-label">State</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Candidate.State)
    </div>

    <div class="display-label">Version Number</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Candidate.VersionNumber)
    </div>

    <div class="display-label">History</div>        
    <div class="display-field">
        @foreach (var historyItem in Model.Candidate.History.Reverse())
        {
            <div>@historyItem.Date: @historyItem.StateChange</div>
        }
    </div>

    <div class="display-label">Deployments</div>        
    <div class="display-field">
        @foreach (var deployment in Model.Candidate.Deployments.Reverse())
        {
            <div>@deployment.Date: @Html.ActionLink(deployment.Environment, "Details", "Environment", new { name = deployment.Environment }, new { })</div>
        }
    </div>
</fieldset>
<p>    
    @Html.ActionLink("Deploy", "Deploy", "ReleaseCandidate", new { versionNumber = Model.Candidate.FullVersion }, new object()) |
    @Html.ActionLink("Download script", "GetScript", "ReleaseCandidateApi", new { versionNumber = Model.Candidate.FullVersion }, new object()) |
    @Html.ActionLink("Edit", "Edit", new { versionNumber = Model.Candidate.FullVersion }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ReleaseCandidateTracker/Views/ReleaseCandidate/Edit.cshtml
@model ReleaseCandidateTracker.Models.ReleaseCandidate
@{
    ViewBag.Title = "Edit release candidate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Change state of @Model.ProductName @Model.VersionNumber</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="display-label">
            Product Name</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ProductName)
        </div>
        <div class="display-label">
            Creation Date (UTC)</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CreationDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.State)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.State, new SelectList(Enum.GetValues(typeof(ReleaseCandidateTracker.Models.ReleaseCandidateState))))
            @Html.ValidationMessageFor(model => model.State)
        </div>
        <div class="display-label">
            Version Number</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.VersionNumber)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ReleaseCandidateTracker/Views/ReleaseCandidate/Index.cshtml
@model ReleaseCandidateTracker.ViewModels.ReleaseCandidateListViewModel

@{
    ViewBag.Title = "Release candidate list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="environmentSummary">
@foreach (var env in Model.Environments)
{
    <span>
         @Html.ActionLink(env.Name, "Details", "Environment", new { name = env.Name }, new object()) : @(env.CurrentVersion != null ? Html.ActionLink(env.CurrentVersion, "Details", new { versionNumber = env.CurrentVersion }) : new HtmlString("n/a"))
    </span>
}
</div>

<h2>Release candidates</h2>

<table>
    <tr>
        <th>
            ProductName
        </th>
        <th>
            CreationDate (UTC)
        </th>
        <th>
            State
        </th>
        <th>
            VersionNumber
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (var item in Model.Items) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VersionNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { versionNumber = item.FullVersion }) |
            @Html.ActionLink("Details", "Details", new { versionNumber = item.FullVersion }) |
            @Html.ActionLink("Deploy", "Deploy", "ReleaseCandidate", new { versionNumber = item.FullVersion }, new object())
        </td>
    </tr>
}
</table>
<div id="nextPage">
@if (!Model.First) {
@Html.ActionLink("<< Prev", "Index", new { page = Model.Page - 1 })
}
@if (!Model.First && !Model.Last) {<text>&nbsp;|&nbsp;</text>}
@if (!Model.Last) {
@Html.ActionLink("Next >>", "Index", new { page = Model.Page + 1 })
}
</div>